<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="NRANGASA-IN" ignored="3" name="Default test" tests="1" failures="1" timestamp="16 Apr 2019 03:06:33 GMT" time="8.278" errors="0">
  <testcase name="testCondition" time="0.012" classname="com.amazon.automation.AmazonHomeTest">
    <failure type="java.lang.IllegalArgumentException" message="resource https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js not found.">
      <![CDATA[java.lang.IllegalArgumentException: resource https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js not found.
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:210)
at com.google.common.io.Resources.getResource(Resources.java:195)
at com.amazon.automation.AmazonHomeTest.testCondition(AmazonHomeTest.java:45)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testCondition -->
  <testcase name="testWatchPoint" time="0.0" classname="com.amazon.automation.AmazonHomeTest">
    <ignored/>
  </testcase> <!-- testWatchPoint -->
  <testcase name="testException" time="0.0" classname="com.amazon.automation.AmazonHomeTest">
    <ignored/>
  </testcase> <!-- testException -->
  <testcase name="testStepFiltering" time="0.0" classname="com.amazon.automation.AmazonHomeTest">
    <ignored/>
  </testcase> <!-- testStepFiltering -->
</testsuite> <!-- Default test -->
