<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="3" total="4" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="8278" started-at="2019-04-16T03:06:24Z" finished-at="2019-04-16T03:06:33Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="8278" started-at="2019-04-16T03:06:24Z" finished-at="2019-04-16T03:06:33Z">
      <class name="com.amazon.automation.AmazonHomeTest">
        <test-method status="PASS" signature="start()[pri:0, instance:com.amazon.automation.AmazonHomeTest@28eaa59a]" name="start" is-config="true" duration-ms="6519" started-at="2019-04-16T03:06:24Z" finished-at="2019-04-16T03:06:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method status="FAIL" signature="testCondition()[pri:0, instance:com.amazon.automation.AmazonHomeTest@28eaa59a]" name="testCondition" duration-ms="12" started-at="2019-04-16T03:06:31Z" description="Conditional break point." finished-at="2019-04-16T03:06:31Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[resource https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js not found.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: resource https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js not found.
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:210)
at com.google.common.io.Resources.getResource(Resources.java:195)
at com.amazon.automation.AmazonHomeTest.testCondition(AmazonHomeTest.java:45)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCondition -->
        <test-method status="PASS" signature="quit()[pri:0, instance:com.amazon.automation.AmazonHomeTest@28eaa59a]" name="quit" is-config="true" duration-ms="1677" started-at="2019-04-16T03:06:31Z" finished-at="2019-04-16T03:06:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- com.amazon.automation.AmazonHomeTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
